blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('study/', include('studyapp.urls')),
    path('project/', include('projectapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('comment/', include('commentapp.urls')),
    path('search/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentPJCreateView

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('createpj/', CommentPJCreateView.as_view(), name='createpj'),
]

commentapp/models.py
from django.db import models

# Create your models here.
from projectapp.models import Project
from studyapp.models import Post


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment')
    writer = models.CharField(max_length=20 ,null=False)
    email = models.EmailField(max_length=50, blank=True, null=True)
    comment_text = models.TextField(null=False)
    create_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.comment_text

class CommentPJ(models.Model):
    post = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='commentpj')
    writer = models.CharField(max_length=20, null=False)
    email = models.EmailField(max_length=50, blank=True, null=True)
    comment_text = models.TextField(null=False)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment_text


    def __str__(self):
        return self.comment_text

commentapp/forms.py
from django.forms import ModelForm

from commentapp.models import Comment, CommentPJ


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['writer', 'email', 'comment_text']



class CommentPJForm(ModelForm):
    class Meta:
        model = CommentPJ
        fields = ['writer', 'email', 'comment_text']

commentapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView

from commentapp.forms import CommentForm, CommentPJForm
from commentapp.models import Comment, CommentPJ
from projectapp.models import Project
from studyapp.models import Post


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'commentapp/create.html'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = Post.objects.get(pk=self.request.POST['post_pk'])
        comment.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('studyapp:studydetail', kwargs={'pk':self.object.post.pk})


class CommentPJCreateView(CreateView):
    model = CommentPJ
    form_class = CommentPJForm
    template_name = 'commentapp/createpj.html'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = Project.objects.get(pk=self.request.POST['project_pk'])
        comment.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('projectapp:projectdetail', kwargs={'pk':self.object.post.pk})

commentapp/templates/commentapp/create.html
{% block content%}
    <form action="{% url 'commentapp:create' %}" method="POST">
      {% csrf_token %}
      <div class="container">
        <div class="row" style="display:flex; flex-direction: column; align-items: center;">
          <img src="/static/assets/comment.png" alt="" class="comment-image">
          <div class="comment-total">
            <div class="comment-box">
              <div class="col-12 md-6">
                <div class="comment-form">
                  <input id="writer" type="text" name="writer" placeholder="이름 or 닉네임" class="comment_name">
                  <input id="email" type="email" name="email" placeholder="이메일" class="comment_email">
                </div>
              </div>
              <div class="col-12">
                <div class="comment-content">
                  <textarea name="comment_text" id="comment_text" rows="10" placeholder="댓글을 입력해주세요." class="test32"
                  onKeyup="var m=50;var s=this.scrollHeight;if(s>=m)this.style.pixelHeight=s+4"></textarea>
                </div>
              </div>
              <input type="submit" class="comment-btn" value="Create">
              <input type="hidden" name="post_pk" value="{{ post.pk }}">
            </div>
          </div>
        </div>
      </div>
    </form>
{% endblock %}

commentapp/templates/commentapp/createpj.html
{% block content%}
    <form action="{% url 'commentapp:createpj' %}" method="POST">
      {% csrf_token %}
      <div class="container">
        <div class="row" style="display:flex; flex-direction: column; align-items: center;">
          <img src="/static/assets/comment.png" alt="" class="comment-image">
          <div class="comment-total">
            <div class="comment-box">
              <div class="col-12 md-6">
                <div class="comment-form">
                  <input id="writer" type="text" name="writer" placeholder="이름 or 닉네임" class="comment_name">
                  <input id="email" type="email" name="email" placeholder="이메일" class="comment_email">
                </div>
              </div>
              <div class="col-12">
                <div class="comment-content">
                  <textarea name="comment_text" id="comment_text" rows="10" placeholder="댓글을 입력해주세요." class="test32"
                  onKeyup="var m=50;var s=this.scrollHeight;if(s>=m)this.style.pixelHeight=s+4"></textarea>
                </div>
              </div>
              <input type="submit" class="comment-btn" value="Create">
              <input type="hidden" name="project_pk" value="{{ project.pk }}">
            </div>
          </div>
        </div>
      </div>
    </form>
{% endblock %}

commentapp/templates/commentapp/detail.html
<section>
    <div class="container">
        <div class="row">
            <div class="col-12" style="  display: flex; flex-direction: column; align-items: center;">
                <div class="comment-detail">
                    <div class="comment-header">
                        <p class="comment-writer">
                            {{ comment.writer }}
                        </p>
                        <p class="comment-date">
                            {{ comment.create_date }}
                        </p>
                    </div>
                    <div class="comment-detail-content">
                        {{ comment.comment_text }}
                    </div>
                    <img src="/static/assets/comment-footer.svg" class="comment-footer-image">
                </div>
            </div>
        </div>
    </div>
</section>









































<!--<div style="border: 1px solid; text-align: left">-->
<!--    <div>-->
<!--        <strong>-->
<!--            {{ comment.writer }}-->
<!--        </strong>-->
<!--        {{ comment.create_date }}-->
<!--    </div>-->
<!--    <div>-->
<!--        {{ comment.comment_text }}-->
<!--    </div>-->
<!--</div>-->