blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('study/', include('studyapp.urls')),
    path('project/', include('projectapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('comment/', include('commentapp.urls')),
    path('search/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from . import views
from .views import Allpost

app_name = 'mainapp'

urlpatterns = [
    path('', Allpost.as_view(), name='hello_main'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectList, ProjectDetail

app_name = 'projectapp'

urlpatterns = [
    path('', ProjectList.as_view(), name='projectview'),
    path('<int:pk>/', ProjectDetail.as_view(), name='projectdetail'),
]

studyapp/urls.py
from django.urls import path


from mainapp import views
from studyapp.views import CategoryView, StudyListView, StudyDetailView

app_name = 'studyapp'

urlpatterns = [
    path('', CategoryView.as_view(), name='studyview'),
    path('<int:pk>/', StudyListView.as_view(), name='studylist'),
    path('detail/<int:pk>/', StudyDetailView.as_view(), name='studydetail'),
]

mainapp/models.py
from django.db import models

# Create your models here.

class Testtext(models.Model):
    text = models.CharField(max_length=100, null=False)

mainapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, TemplateView

from projectapp.models import Project
from studyapp.models import Post



class Allpost(ListView):
    model = Project
    context_object_name = 'project_post'
    template_name = 'mainapp/main.html'

    def get_queryset(self):
        context = Project.objects.all().order_by('-created_date')[:5]
        return context

    def get_context_data(self, **kwargs):
        context = super(Allpost, self).get_context_data(**kwargs)
        context['study_post'] = Post.objects.all().order_by('-created_date')[:9]
        return context

mainapp/templates/mainapp/main.html
{% extends 'base.html' %}

{% block content %}
    <section class="banner">
        <div class="banner-total">
          <div class="banner-image">
            <img src="/static/assets/welcome.svg" alt="">
          </div>
          <div class="banner-content">
            <p>
              Welcome !<br>
              This is my first website and
              my personal blog site.
            </p>
          </div>
        </div>
    </section>


    <section class="card">
        <div class="container">
          <div class="row">
            <div class="col-12 md-4">
            <h2 class="list-title">Post</h2>
              <div class="card-total">
              {% if study_post %}
              {% for post in study_post %}
              <a href="{% url 'studyapp:studydetail' post.pk %}">
                  <div class="card-list">
                      <div class="card-text">
                        <div class="post-content-img">
                            <img src="{{ post.content_image.url }}" alt="">
                            <h2>{{ post.post_title }}</h2>
                        </div>
                        <div class="card-header">
                          <img src="{{ post.profile_image.url }}" alt="" class="profile-image">
                          <div class="post-header">
                            <strong class="post-username">{{ post.user }}</strong>
                            <p class="post-date">{{ post.updated_date|date:'Y-m-d' }}</p>
                          </div>
                        </div>
                        <div class="post-content">
                          <p>{{ post.sub_content | safe | truncatechars:150 }}</p>
                        </div>
                      </div>
                  </div>
              </a>
              {% endfor %}
              {% else %}
                  <h1 style="font-size:40px; font-weight: 200; margin: 50px 0;">There are no posts yet.</h1>
              {% endif %}
              </div>
            </div>
          </div>
        </div>
    </section>

    <section class="project">
      <div class="container">
        <div class="row">
          <div class="col-12">
          <h2 class="list-title">Project</h2>
            <div class="project-content">
              <div class="slide_wrapper">
                  <ul class="slides">
                  {% if project_post %}
                  {% for project in project_post %}
                      <a href="{% url 'projectapp:projectdetail' project.pk %}">
                        <li class="slide-list">
                            <img src="{{ project.content_image.url }}" alt="" class="slide-image">
                            <h2 class="slide-title">{{ project.title }}</h2>
                            <p class="slide-date">{{ project.created_date|date:'Y-m-d' }}</p>
                        </li>
                      </a>
                  {% endfor %}
                </ul>
              </div>
              <div class="controls">
                <div class="prev"><i class="fas fa-arrow-left"></i></div>
                <div class="next"><i class="fas fa-arrow-right"></i></div>
              </div>
                  {% else %}
                  <h1 style="font-size:40px; font-weight: 200; margin: 50px 0 50px 350px; text-align:center;">
                      There are no project yet.</h1>
                  {% endif %}
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class=charts-total>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="chart-title">
              <h1>Language</h1>
            </div>
            <div class="charts">
              <div class="chart">
                <h2 data-num="10">0</h2>
                <svg>
                  <circle cx="110" cy="110" r="100"></circle>
                </svg>
                <p>HTML</p>
              </div>
              <div class="chart">
                <h2 data-num="10">0</h2>
                <svg>
                  <circle cx="110" cy="110" r="100" class="chart-line"></circle>
                </svg>
                <p>CSS</p>
              </div>
              <div class="chart">
                <h2 data-num="20">0</h2>
                <svg>
                  <circle cx="110" cy="110" r="100" class="chart-line"></circle>
                </svg>
                <p>Python</p>
              </div>
              <div class="chart">
                <h2 data-num="60">0</h2>
                <svg>
                  <circle cx="110" cy="110" r="100"></circle>
                </svg>
                <p>JavaScript</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="footer-image">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="footer-image-total">
              <img src="/static/assets/footer_total.svg" alt="" class="main-footer">
            </div>
          </div>
        </div>
      </div>
    </section>
    <script src="/static/js/charts.js"></script>
    <script src="/static/js/slide.js"></script>
{% endblock %}