blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('study/', include('studyapp.urls')),
    path('project/', include('projectapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('comment/', include('commentapp.urls')),
    path('search/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from . import views
from .views import Allpost

app_name = 'mainapp'

urlpatterns = [
    path('', Allpost.as_view(), name='hello_main'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProjectList

app_name = 'profileapp'

urlpatterns = [
     path('', ProjectList.as_view(), name='projectlist'),
]

searchapp/urls.py
from django.urls import path

from searchapp.views import SearchFormView

app_name = 'searchapp'

urlpatterns = [
    path('', SearchFormView.as_view(), name='search'),
]

studyapp/urls.py
from django.urls import path


from mainapp import views
from studyapp.views import CategoryView, StudyListView, StudyDetailView

app_name = 'studyapp'

urlpatterns = [
    path('', CategoryView.as_view(), name='studyview'),
    path('<int:pk>/', StudyListView.as_view(), name='studylist'),
    path('detail/<int:pk>/', StudyDetailView.as_view(), name='studydetail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="footer-total">
              <h1 class="footer-title">Grape's Blog<i class="fas fa-leaf"></i></h1>
              <p class="footer-content">Python, Django, Javascript, Data Analysis등 웹 개발 및 IT 관련된 내용을 다룹니다.</p>
              <ul class="footer-links">
                <li><a href="https://www.instagram.com/jd.bxxm/" target="_blank"><i class="fab fa-instagram"></i></a></li>
                <li><a href="https://www.facebook.com/profile.php?id=100012555663281" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="https://github.com/grape-git" target="_blank"><i class="fab fa-github"></i></a></li>
              </ul>
              <p class="footer-last">2021 Since</p>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Grape Blog</title>

    <!-- google font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;700;900&display=swap" rel="stylesheet">

    <!-- base css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

    <!-- grid css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/grid.css' %}">

    <!-- grid css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <!-- study list css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/category.css' %}">

    <!-- target study list css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/study_list.css' %}">

    <!-- target study list css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/study_detail.css' %}">

    <!-- target study list css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/pagination.css' %}">

    <!-- project list css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/project_list.css' %}">

    <!-- profile list css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

    <!-- comment form css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/comment.css' %}">

    <!-- comment detail css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/comment_detail.css' %}">

    <!-- comment detail css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">

    <!-- js -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>

    <!-- icon -->
    <script src="https://kit.fontawesome.com/28c205a363.js" crossorigin="anonymous"></script>
</head>

templates/header.html
<head>
    <link rel="shortcut icon" href="#">
</head>
<nav class="navbar">
        <div class="nav-list">
        <a href="javascript:;" class="fas fa-bars"  id="menuBtn"><i></i></a>
        <h2 class="title" id="menuTitle"></h2>
        <span class="usrInfo">
        <a href="javascript:;" id="userName"></a>
        </span>
        <aside class="sideBar">
        <nav class="menu">
          <a href="javascript:;" class="menuClose">X</a>
          <ul class="depth_application" id ="menuList">
              <li><a href="{% url 'mainapp:hello_main' %}"><i class="fas fa-home"></i>Home</a></li>
              <li><a href="{% url 'profileapp:projectlist' %}"><i class="fas fa-user-circle"></i>Profile</a></li>
              <li><a href="{% url 'projectapp:projectview' %}"><i class="fas fa-lightbulb"></i>Project</a></li>
              <li><a href="{% url 'studyapp:studyview' %}"><i class="fas fa-book"></i>Study</a></li>
          </ul>
          </nav>
        </aside>
        </div>
        <ul class="nav-menu">
          <li><a href="{% url 'mainapp:hello_main' %}"><img src="/static/assets/grape02.png" alt="" class="grape"/></a></li>
          <li><a href="{% url 'profileapp:projectlist' %}"><img src="/static/assets/user01.png" alt=""/></a></li>
          <li><a href="{% url 'projectapp:projectview' %}"><img src="/static/assets/project01.png" alt=""/></a></li>
          <li><a href="{% url 'studyapp:studyview' %}"><img src="/static/assets/book02.png" alt=""/></a></li>
          <li><a href="/admin/"><i class="fas fa-user-cog"></i></a></li>
        </ul>
        <div class="nav-search">
            <a href="{% url 'searchapp:search' %}"><i class="fas fa-search"></i></a>
        </div>
    </nav>
    <script layout:fragment="pageScript" th:inline="javascript">
        $(function() {
          $('#menuBtn').on('click', function(){
            $('.sideBar').toggleClass('open');
            $('.menu').toggleClass('active');
            $('body').css('overflow', 'hidden');
          });

          // Menu Close
          $('.menuClose').on('click', function(){
            $('.sideBar').toggleClass('open');
            $('.menu').removeClass('active');
            $('body').css('overflow', 'visible');
          });

          $(".sideBar").click(function (e) {
            $('.sideBar').toggleClass('open');
            $('.menu').removeClass('active');
            $('body').css('overflow', 'visible');
          });

          $(".menu").click(function (e) {
          e.stopPropagation();
          });

        });
    </script>