blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('mainapp.urls')),
    path('study/', include('studyapp.urls')),
    path('project/', include('projectapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('comment/', include('commentapp.urls')),
    path('search/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studyapp/urls.py
from django.urls import path


from mainapp import views
from studyapp.views import CategoryView, StudyListView, StudyDetailView

app_name = 'studyapp'

urlpatterns = [
    path('', CategoryView.as_view(), name='studyview'),
    path('<int:pk>/', StudyListView.as_view(), name='studylist'),
    path('detail/<int:pk>/', StudyDetailView.as_view(), name='studydetail'),
]

studyapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    study_title = models.CharField(max_length=50, null=False)
    study_image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.study_title

class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    profile_image = models.ImageField(upload_to='profile/', blank=True, null=True)
    post_title = models.CharField(max_length=50, null=False)
    sub_content = models.CharField(max_length=100, null=True)
    post_content = models.TextField(null=False)
    content_image = models.ImageField(upload_to='content_image/', blank=True, null=True)
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.post_title

studyapp/views.py
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from commentapp.forms import CommentForm
from commentapp.models import Comment
from studyapp.models import Category, Post
from rest_framework.pagination import PageNumberPagination

class CategoryView(ListView):
    model = Category
    context_object_name = 'study_list'
    template_name = 'studyapp/list.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context


class StudyListView(ListView):
    model = Post
    context_object_name = 'target_list'
    template_name = 'studyapp/studylist.html'
    paginate_by = 9

    def get_queryset(self):
        queryset = Post.objects.filter(category_id=self.kwargs['pk']).order_by('-created_date')
        return queryset


    def get_context_data(self, **kwargs):
        context = super(StudyListView, self).get_context_data(**kwargs)
        paginator = context['paginator']
        context['target_study_list'] = Category.objects.filter(id=self.kwargs['pk'])[:1]
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context



class StudyDetailView(DetailView, FormMixin):
    model = Post
    form_class = CommentForm
    context_object_name = 'target_study_detail'
    template_name = 'studyapp/studydetail.html'

studyapp/templates/studyapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="study-banner">
        <div class="study-banner-total">
          <div class="study-banner-img">
              <img src="/static/assets/study_list.svg" alt="">
          </div>
        </div>
    </section>

    <section class="study-card">
        <div class="container">
          <div class="row">
            <div class="col-12 md-4">
            <h2 class="list-title">Category</h2>
              <div class="study-card-total">
                    {% if study_list %}
                        {% for list in study_list %}
                        <div class="study-card-list">
                            <a href="{% url 'studyapp:studylist' list.pk %}">
                                <h2 class="study-card-title">{{ list.study_title }}</h2>
                                <p class="study-card-image">
                                <img src="{{ list.study_image.url }}" alt="">
                             </a>
                            </p>
                        </div>
                        {% endfor %}
                    {% else %}
                      <h1 style="font-size:40px; font-weight: 200; margin: 200px 0; text-align:center;">
                      There are no Category yet.</h1>
                    {% endif %}
              </div>
            </div>
          </div>
        </div>
    </section>

    {% if is_paginated %}
      <nav aria-label="Page navigation example">
          <div class="page-total">
            <ul class="pagination">
              {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <li>
                        <i class="fas fa-chevron-left"></i>
                    </li>
                </a>
              {% else %}
                <a href="#" class="page-link">
                    <li class="page-item">
                        <i class="fas fa-chevron-left"></i>
                    </li>
                </a>
              {% endif %}

              {% for page in page_range %}
                <a class="page-link" href="?page={{ page }}">
                <li class="page-item" {% if page == page_obj.number %}class="active"{% endif %}>
                    {{ page }}
                </li>
                </a>
              {% endfor %}

              {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <li class="page-item">
                        <i class="fas fa-chevron-right"></i>
                    </li>
                </a>
              {% else %}
                <a class="page-link" href="#">
                    <li class="page-item" {% if not page_obj.has_next %}class="disabled"{% endif %}>
                        <i class="fas fa-chevron-right"></i>
                    </li>
                </a>
              {% endif %}
            </ul>
          </div>
      </nav>
    {% endif %}
{% endblock %}

studyapp/templates/studyapp/studydetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="detail-banner">
              <div class="content-image">
                <img src="/static/assets/img03.png" alt="">
              </div>
    </section>

    <section class="detail-content">
      <div class="container">
        <div class="row">
          <div class="col-12">
              <div class="detail-content-total">
                <div class="detail-post">
                {% if target_study_detail %}
                    <div class="detail-content-header">
                        <h1>{{ target_study_detail.post_title }}</h1>
                        <p>{{ target_study_detail.updated_date }}</p>
                    </div>
                    <div class="detail-content-content">
                        <p>{{ target_study_detail.post_content | safe  }}</p>
                </div>
                {% endif %}
                </div>
              </div>
          </div>
        </div>
      </div>
    </section>

    {% for comment in target_study_detail.comment.all %}
        {% include 'commentapp/detail.html' with comment=comment %}
    {% endfor %}

    {% include 'commentapp/create.html' with post=target_study_detail %}
{% endblock %}

studyapp/templates/studyapp/studylist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="study-list-banner">
        {% for target in  target_study_list %}
        <div class="study-list-banner-total">
          <img src="{{ target.study_image.url }}" alt="" class="study-list-image">
          <h2 class="study-list-banner-title">
              {{ target.study_title }}
          </h2>
        </div>
        {% endfor %}
    </section>

    <section class="card">
        <div class="container">
          <div class="row">
            <div class="col-12 md-4">
            <h2 class="list-title">Post</h2>
              <div class="card-total">
              {% if target_list %}
              {% for target_study in target_list %}
              <a href="{% url 'studyapp:studydetail' target_study.pk %}">
                  <div class="card-list">
                      <div class="card-text">
                        <div class="post-content-img">
                            <img src="{{ target_study.content_image.url }}" alt="">
                            <h2>{{ target_study.post_title }}</h2>
                        </div>
                        <div class="card-header">
                          <img src="{{ target_study.profile_image.url }}" alt="" class="profile-image">
                          <div class="post-header">
                            <strong class="post-username">{{ target_study.user }}</strong>
                            <p class="post-date">{{ target_study.updated_date|date:'Y-m-d' }}</p>
                          </div>
                        </div>
                        <div class="post-content">
                          <p>{{ target_study.sub_content | truncatechars:150 | safe }}</p>
                        </div>
                      </div>
                  </div>
              </a>
              {% endfor %}
              {% else %}
                <h1 style="font-size:40px; font-weight: 200; margin: 200px 0; text-align:center;">
                      There are no Post yet.</h1>
              {% endif %}
              </div>
            </div>
          </div>
        </div>
    </section>

    {% if is_paginated %}
      <nav aria-label="Page navigation example">
          <div class="page-total">
            <ul class="pagination">
              {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <li>
                        <i class="fas fa-chevron-left"></i>
                    </li>
                </a>
              {% else %}
                <a href="#" class="page-link">
                    <li class="page-item">
                        <i class="fas fa-chevron-left"></i>
                    </li>
                </a>
              {% endif %}

              {% for page in page_range %}
                <a class="page-link" href="?page={{ page }}">
                <li class="page-item" {% if page == page_obj.number %}class="active"{% endif %}>
                    {{ page }}
                </li>
                </a>
              {% endfor %}

              {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <li class="page-item">
                        <i class="fas fa-chevron-right"></i>
                    </li>
                </a>
              {% else %}
                <a class="page-link" href="#">
                    <li class="page-item" {% if not page_obj.has_next %}class="disabled"{% endif %}>
                        <i class="fas fa-chevron-right"></i>
                    </li>
                </a>
              {% endif %}
            </ul>
          </div>
      </nav>
    {% endif %}
{% endblock %}